version: '2.1'

services:
  eureka-server:
    build: eureka-server/
    depends_on:
      config-service:
        condition: service_healthy
    restart: always
    network_mode: "host"
    image: demo-eureka-service
    hostname: localhost
    ports:
      - 9090:9090
    healthcheck:
      test: "exit 0"

  config-service:
   build: config-service/
   restart: always
   network_mode: "host"
   image: demo-config-service
   hostname: localhost
   ports:
    - 8891:8891
   healthcheck:
    test: "exit 0"

  api-gateway:
   build: zuul-apigateway/
   depends_on:
    config-service:
     condition: service_healthy
    eureka-server:
     condition: service_healthy
    restart: always
    network_mode: "host"
    image: demo-zuul-service
    hostname: localhost
    ports:
     - 8092:8092
    healthcheck:
     test: "exit 0"
  

  userprofile:
   image: thoopalliamar/userprofile:1.0
   restart: always
   network_mode: host
   container_name: userprofile
   depends_on:
    - mongo
   ports:
    - 8040:8040
   healthcheck:
    test: "exit 0"

      
      
  spring:
   image: leelamaithreyi/theatre-registration:1.0
   restart: always
   network_mode: host
   container_name: spring-docker
   depends_on:
     - mongo
   ports:
     - 8020:8020
   healthcheck:
      test: "exit 0"
      
      
   spring:
    image: sakethmaringanti/movie-schedule:1.0
    restart: always
    network_mode: host
    container_name: spring-docker
    depends_on:
      - mongo
    ports:
      - 8030:8030
    healthcheck:
      test: "exit 0"  
    
login-auth:
   build: login-authentication/
   image: login
   restart: always
   network_mode: host
   hostname: localhost
   container_name: login-authentication-docker
   depends_on:
    - mysql
   ports:
    - 8070:8070
   healthcheck:
      test: "exit 0"
     
  mysql:
   image: mysql:5.7
   ports:
    - "3306:3306"
   container_name: mysql-docker
   network_mode: host
   hostname: localhost
   environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: juggler_db
      MYSQL_PASSWORD: root
   healthcheck:
      test: "exit 0"
 
 
