version: '2.1'

services:

  userprofile:

   build: user-profile/

   restart: always

   network_mode: host

   container_name: userprofile


   ports:

    - 8040:8040

   healthcheck:

    test: "exit 0"


  screening:

   build: movie-schedule/

   restart: always

   network_mode: host

   container_name: screening



   ports:

    - 8030:8030

   healthcheck:

    test: "exit 0"




  theatre:

   build: theatre-registration/

   restart: always

   network_mode: host

   container_name: theatre



   ports:

    - 8020:8020

   healthcheck:

    test: "exit 0"




  login:
   
   build: login-authentication/
   restart: always

   network_mode: "host"
   hostname: localhost
   ports:
    - 8070:8070
   container_name: auth

   healthcheck:
    test: "exit 0"




  distributor:
   
   build: distributor/

   restart: always

   network_mode: "host"

   hostname: localhost

   ports:
    - 8010:8010

   container_name: distributor



   healthcheck:
    test: "exit 0"


  recommendations:
   
   build: recommendation/

   restart: always

   network_mode: "host"
   hostname: localhost
   ports:
    - 8050:8050
   container_name: recommendations

   healthcheck:
    test: "exit 0"

  search:
   
   build: movie-search/
   restart: always

   network_mode: "host"
   hostname: localhost
   ports:
    - 8060:8060
   container_name: search

   healthcheck:
    test: "exit 0"


 












