version: '2.1'
services:
  eureka-server:
    build: eureka-server/
    depends_on:
      config-service:
        condition: service_healthy
    restart: always
    network_mode: "host"
    image: demo-eureka-service
    hostname: localhost
    ports:
      - 9090:9090
    healthcheck:
      test: "exit 0"

  config-service:
   build: config-service/
   restart: always
   network_mode: "host"
   image: demo-config-service
   hostname: localhost
   ports:
    - 8891:8891
   healthcheck:
    test: "exit 0"

  api-gateway:
   build: zuul-apigateway/
   depends_on:
    config-service:
     condition: service_healthy
    eureka-server:
     condition: service_healthy
   restart: always
   network_mode: "host"
   image: demo-zuul-service
   hostname: localhost
   ports:
    - 8092:8092
   healthcheck:
    test: "exit 0"
  
  login-auth:
   build: login-authentication/
   container_name: login-authentication-docker
   depends_on:
    - mysql
   healthcheck:
    test: exit 0
   hostname: localhost
   image: login
   network_mode: host
   ports:
    - 8070:8070
   restart: always

  mysql:
   container_name: mysql-docker
   image: mysql:5.7
   ports:
    - 3306:3306
   network_mode: host
   hostname: localhost
   environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: juggler_db
    MYSQL_PASSWORD: root
   healthcheck:
    test: exit 0
   
   
   
   
  
