server:
  port: "9073"


spring:
  data:
    mongodb:
      database: showdb
      host: localhost
      port: "27017"
      uri: mongodb://localhost/showdb
      username: ""
  application:
    name: ticketengine