# Loco yaml export: Symfony YAML object
# Project: application.properties conversion
# Release: Working copy
# Locale: te-IN, Telugu (India)
# Exported by: Unregistered user
# Exported at: Wed, 29 Aug 2018 18:09:15 +0530
---
server:
  port: "8040"
spring:
  data:
    mongodb:
      database: userdb
      host: localhost
      port: "27017"
      uri: mongodb://localhost/userdb
      username: ""
  application:
    name: UserProfile
  cloud:
    config:
      uri: http://localhost:8891
eureka:
  client:
    register-with-eureka: "true"
    fetch-registry: "true"
    serviceUrl:
      defaultZone: http://localhost:9090/eureka/
...
