server:
 port: 8070
spring:
  datasource:
    url:  jdbc:mysql://localhost:3306/juggler_db
    username: root
    password: root123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  application:
   name: authentication  
  properties:
   hibernate:
    dialect: org.hibernate.dialect.MySQL5Dialect
       
       
#eureka:
# client:
#   register-with-eureka:true
#   fetch-registry:true
# serviceUrl:
#   defaultZone:http://localhost:9090/eureka