port: 8070
spring:
  datasource:
    url:  jdbc:mysql://localhost:3306/juggler_db
    username: root
    password: vish123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      
      
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect