server:
  port: "8010"
spring:
  data:
    mongodb:
      database: distributormovie
      host: localhost
      port: "27017"
      uri: mongodb://localhost/distributormovie
      username: ""
  application:
    name: distributor
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9090/eureka
    register-with-eureka: "true"
    fetch-registry: "true"